local spiral_split = require("spiral-split")
spiral_split.setup()

describe("is_vertical", function()
	it("ok", function()
		local height = vim.api.nvim_win_get_height(0)
		vim.cmd(height + 50 .. "vsplit")
		assert(spiral_split.is_vertical())
		vim.cmd("close")
	end)
end)

describe("is_horizontal", function()
	it("ok", function()
		local height = vim.api.nvim_win_get_height(0)
		vim.cmd(height - 1 .. "vsplit")
		assert(spiral_split.is_horizontal())
		vim.cmd("close")
	end)
end)
