name: Selene check
'on':
  push:
    branches:
      - main
  pull_request: null
jobs:
  selene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Selene check
        uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          args: lua/ tests/
          version: 0.20.0

