name: Stylua check
'on':
  push:
    branches:
      - main
  pull_request: null
jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Stylua check
        uses: JohnnyMorganz/stylua-action@v1.1.1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          args: '--check .'
          version: 0.15.0

